FROM ubuntu:22.04

RUN useradd -u 1010 db2inst1

COPY createdb.sh .
RUN chmod a+x ./createdb.sh 

RUN chown -R db2inst1:db2inst1 /opt
RUN chown db2inst1:db2inst1 createdb.sh

USER 1010

ENV PATH="/opt/mssql-tools/bin:${PATH}"