apiVersion: batch/v1
kind: Job
metadata:
  namespace: tools
  annotations:
    argocd.argoproj.io/sync-wave: "285"
    # we need to fix the syn wave to be less than sterling-deployment
  name: "ibm-odm-psp"
  labels:
    app: "ibm-odm-psp"
spec:
  template:
    spec:
      serviceAccountName: account-tools-cp4a-db2-instance
      containers:
      - name: "odm-db2-create-tables"
        securityContext:
          runAsUser: 1010
        image: raafatadly/create-db2-odm:1.0.0
        imagePullPolicy: Always
        command: ["bash"]
        args:
          - "-c"
          - "export ldap_pod=$(oc get pods -l role=ldap -o name)"
          - "oc rsh ${ldap_pod} /bin/bash"
          - "/opt/ibm/ldap_scripts/addLdapUser.py -u icnadm -p Passw0rd -r user"
          - "/opt/ibm/ldap_scripts/addLdapUser.py -u odmadm -p Passw0rd -r user"
      restartPolicy: Never
  backoffLimit: 4